# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cleanUp <- function() {
    invisible(.Call(`_jaspSyntax_cleanUp`))
}

shutdownNative <- function() {
    invisible(.Call(`_jaspSyntax_shutdownNative`))
}

clearQmlFormsNative <- function() {
    invisible(.Call(`_jaspSyntax_clearQmlFormsNative`))
}

clearDatasetStateNative <- function() {
    invisible(.Call(`_jaspSyntax_clearDatasetStateNative`))
}

clearNativeStateNative <- function() {
    invisible(.Call(`_jaspSyntax_clearNativeStateNative`))
}

setParameter <- function(name, value) {
    .Call(`_jaspSyntax_setParameter`, name, value)
}

loadDataSet <- function(data) {
    invisible(.Call(`_jaspSyntax_loadDataSet`, data))
}

loadQmlAndParseOptions <- function(moduleName, analysisName, qmlFile, options, version, preloadData) {
    .Call(`_jaspSyntax_loadQmlAndParseOptions`, moduleName, analysisName, qmlFile, options, version, preloadData)
}

generateModuleWrappers <- function(modulePath) {
    .Call(`_jaspSyntax_generateModuleWrappers`, modulePath)
}

parseDescription <- function(modulePath) {
    .Call(`_jaspSyntax_parseDescription`, modulePath)
}

loadDataSetFromJaspFile <- function(jaspFilePath) {
    invisible(.Call(`_jaspSyntax_loadDataSetFromJaspFile`, jaspFilePath))
}

analysisOptionsFromJaspFile <- function(jaspFilePath, analysisNr) {
    .Call(`_jaspSyntax_analysisOptionsFromJaspFile`, jaspFilePath, analysisNr)
}

generateAnalysisWrapper <- function(modulePath, analysisName) {
    .Call(`_jaspSyntax_generateAnalysisWrapper`, modulePath, analysisName)
}

getVariableNames <- function() {
    .Call(`_jaspSyntax_getVariableNames`)
}

